[project]
name = "postmodern"
version = "0.1.0"
description = "Example monorepo using uv"
readme = "README.md"
requires-python = "== 3.14.*"
dependencies = []

[tool.uv]
required-version = "==0.9.18"

[tool.uv.workspace]
members = ["libs/*", "apps/*"]
